Repository FEChallenge/challenges, pull requests merged in 2023-08, with the labels that each got.

#9 [Hemdi] 2주차 챌린지
  2-digital-clock/.babelrc.json
  2-digital-clock/.eslintrc.js
  2-digital-clock/.gitignore
  2-digital-clock/.prettierrc
  2-digital-clock/.storybook/main.ts
  2-digital-clock/.storybook/preview.ts
  2-digital-clock/README.md
  2-digital-clock/package.json
  2-digital-clock/postcss.config.js
  2-digital-clock/public/favicon.ico
  2-digital-clock/public/index.html
  2-digital-clock/public/logo192.png
  2-digital-clock/public/logo512.png
  2-digital-clock/public/manifest.json
  2-digital-clock/src/App.tsx
  2-digital-clock/src/components/Button/index.stories.tsx
  2-digital-clock/src/components/Button/index.tsx
  2-digital-clock/src/components/Clock/ActionBox/index.tsx
  2-digital-clock/src/components/Clock/index.stories.tsx
  2-digital-clock/src/components/Clock/index.tsx
  2-digital-clock/src/components/DigitalNumber/Segment/index.stories.tsx
  2-digital-clock/src/components/DigitalNumber/Segment/index.tsx
  2-digital-clock/src/components/DigitalNumber/index.stories.tsx
  2-digital-clock/src/components/DigitalNumber/index.tsx
  2-digital-clock/src/components/TimePanel/Separator/index.stories.tsx
  2-digital-clock/src/components/TimePanel/Separator/index.tsx
  2-digital-clock/src/components/TimePanel/index.stories.tsx
  2-digital-clock/src/components/TimePanel/index.tsx
  2-digital-clock/src/components/ToggleButton/index.stories.tsx
  2-digital-clock/src/components/ToggleButton/index.tsx
  2-digital-clock/src/constants/clock.ts
  2-digital-clock/src/hooks/useInterval.tsx
  2-digital-clock/src/index.tsx
  2-digital-clock/src/tailwind.css
  2-digital-clock/src/utils/time.ts
  2-digital-clock/tailwind.config.js
  2-digital-clock/tsconfig.json
  2-digital-clock/yarn.lock
Labels: 2nd

#6 [Bangtae] 2주차 챌린지
  2-digital-clock/README.md
  2-digital-clock/project/.eslintrc.cjs
  2-digital-clock/project/.gitignore
  2-digital-clock/project/.prettierrc.json
  2-digital-clock/project/README.md
  2-digital-clock/project/index.html
  2-digital-clock/project/package-lock.json
  2-digital-clock/project/package.json
  2-digital-clock/project/src/App.tsx
  2-digital-clock/project/src/GlobalStyle.ts
  2-digital-clock/project/src/components/FourDigitClock.tsx
  2-digital-clock/project/src/components/SevenSegment.tsx
  2-digital-clock/project/src/components/common/Flex.tsx
  2-digital-clock/project/src/components/common/Toggle.tsx
  2-digital-clock/project/src/constants/colors.ts
  2-digital-clock/project/src/hooks/useClock.ts
  2-digital-clock/project/src/hooks/useTimer.ts
  2-digital-clock/project/src/main.tsx
  2-digital-clock/project/src/vite-env.d.ts
  2-digital-clock/project/tsconfig.json
  2-digital-clock/project/tsconfig.node.json
  2-digital-clock/project/vite.config.ts
Labels: 2nd

#13 [Oliver] 3rd 챌린지 제출합니다.
  3-star-rating/assets/emptystar.svg
  3-star-rating/assets/fullstar.svg
  3-star-rating/assets/halfstar.svg
  3-star-rating/index.html
  3-star-rating/src/reset.css
  3-star-rating/src/script.js
  3-star-rating/src/style.css
Labels: 3rd

#12 [Bangtae] 3rd 챌린지
  3-star-rating/project/README.md
  3-star-rating/project/index.html
  3-star-rating/project/src/app.js
  3-star-rating/project/src/script.js
  3-star-rating/project/src/star.js
  3-star-rating/project/src/style.css
  3-star-rating/src/script.js
  3-star-rating/src/style.css
Labels: 3rd

#8 [Oliver] 2주차 챌린지
  2-digital-clock/.gitignore
  2-digital-clock/README.md
  2-digital-clock/package-lock.json
  2-digital-clock/package.json
  2-digital-clock/public/index.html
  2-digital-clock/src/App.tsx
  2-digital-clock/src/components/AMPMIndicator.tsx
  2-digital-clock/src/components/Clock.tsx
  2-digital-clock/src/components/ClockControlBtn.tsx
  2-digital-clock/src/components/Display.tsx
  2-digital-clock/src/components/Dot.tsx
  2-digital-clock/src/components/Hexagon.tsx
  2-digital-clock/src/components/Layout.tsx
  2-digital-clock/src/components/ModeSwitch.tsx
  2-digital-clock/src/components/SevenSegment.tsx
  2-digital-clock/src/components/Spacing.tsx
  2-digital-clock/src/components/TimerControlBtn.tsx
  2-digital-clock/src/hooks/useInterval.ts
  2-digital-clock/src/index.tsx
  2-digital-clock/tsconfig.json
Labels: 2nd

#11 [rumka] 세 번째 챌린지
  3-star-rating/index.html
  3-star-rating/src/components/FiveStar/FiveStar.js
  3-star-rating/src/components/RatingForm/RatingForm.js
  3-star-rating/src/components/Star/Star.js
  3-star-rating/src/constants/message.js
  3-star-rating/src/script.js
  3-star-rating/src/style.css
Labels: 3rd

#16 [rumka] 4번째 챌린지
  4-presentation/.gitignore
  4-presentation/package-lock.json
  4-presentation/package.json
  4-presentation/public/index.html
  4-presentation/src/App.tsx
  4-presentation/src/components/AddPictureButton/AddPictureButton.tsx
  4-presentation/src/components/Carousel/Carousel.tsx
  4-presentation/src/components/Thumbnail/Thumbnail.tsx
  4-presentation/src/components/ThumbnailList/ThumbnailList.tsx
  4-presentation/src/components/common/InputFile/InputFile.tsx
  4-presentation/src/hooks/useFileReader.ts
  4-presentation/src/hooks/useRouter.ts
  4-presentation/src/index.tsx
  4-presentation/src/pages/Home/Home.tsx
  4-presentation/src/pages/Presentation/Presentation.tsx
  4-presentation/src/route.tsx
  4-presentation/src/store/pictures.ts
  4-presentation/src/styles/GlobalStyle.ts
  4-presentation/src/styles/color.ts
  4-presentation/src/styles/commonStyle.ts
  4-presentation/src/styles/components/PageWrapper.styled.ts
  4-presentation/src/utils/util.ts
  4-presentation/tsconfig.json
Labels: 4th

#21 [Oliver] 5th 챌린지 제출
  5-toast-notification/index.html
  5-toast-notification/src/script.js
  5-toast-notification/src/style.css
Labels: 5th

#22 [rumka] 5th 챌린지
  5-toast-notification/index.html
  5-toast-notification/src/controller/NotificationController.js
  5-toast-notification/src/model/NotificationModel.js
  5-toast-notification/src/script.js
  5-toast-notification/src/style.css
  5-toast-notification/src/util.js
  5-toast-notification/src/view/Button.js
  5-toast-notification/src/view/NotificationView.js
  5-toast-notification/src/view/ToastMessage.js
Labels: 5th

#10 [Hemdi] 세 번째 챌린지
  3-star-rating/.gitignore
  3-star-rating/index.html
  3-star-rating/src/App.js
  3-star-rating/src/components/Message.js
  3-star-rating/src/components/StarRatingItem.js
  3-star-rating/src/components/StarRatingList.js
  3-star-rating/src/components/core/Component.js
  3-star-rating/src/index.js
  3-star-rating/src/script.js
  3-star-rating/src/style.css
  3-star-rating/styles/css/style.css
  3-star-rating/styles/css/style.css.map
  3-star-rating/styles/scss/_layout.scss
  3-star-rating/styles/scss/_reset.scss
  3-star-rating/styles/scss/_star-rating.scss
  3-star-rating/styles/scss/style.scss
Labels: 3rd

#17 [hemdi] 4번째 챌린지
  4-presentation/.eslintrc.cjs
  4-presentation/.gitignore
  4-presentation/.storybook/main.ts
  4-presentation/.storybook/preview.ts
  4-presentation/index.html
  4-presentation/package.json
  4-presentation/postcss.config.js
  4-presentation/public/vite.svg
  4-presentation/src/App.tsx
  4-presentation/src/components/FileImage/index.tsx
  4-presentation/src/components/ImageUploader/index.stories.tsx
  4-presentation/src/components/ImageUploader/index.tsx
  4-presentation/src/components/Slider/index.tsx
  4-presentation/src/index.css
  4-presentation/src/main.tsx
  4-presentation/src/pages/MainPage/index.tsx
  4-presentation/src/pages/SliderPage/index.tsx
  4-presentation/src/store/image.tsx
  4-presentation/src/store/slider.tsx
  4-presentation/src/vite-env.d.ts
  4-presentation/tailwind.config.js
  4-presentation/tsconfig.json
  4-presentation/tsconfig.node.json
  4-presentation/vite.config.ts
  4-presentation/yarn.lock
Labels: 4th

#14 [DOTORI] 세번째 챌린지
  3-star-rating/index.html
  3-star-rating/src/js/app.js
  3-star-rating/src/js/components/Rating.js
  3-star-rating/src/js/components/Star.js
  3-star-rating/src/js/constants/index.js
  3-star-rating/src/js/main/index.js
  3-star-rating/src/js/utils/index.js
  3-star-rating/src/script.js
  3-star-rating/src/style.css
  3-star-rating/src/styles/style.css
Labels: 3rd

#18 [DOTORI] 4번째 챌린지
  4-presentation/my-app/.eslintrc.js
  4-presentation/my-app/.prettierrc
  4-presentation/my-app/package-lock.json
  4-presentation/my-app/package.json
  4-presentation/my-app/public/index.html
  4-presentation/my-app/src/App.tsx
  4-presentation/my-app/src/components/Presentation/Slider/Contorller/FileAdder.tsx
  4-presentation/my-app/src/components/Presentation/Slider/Contorller/FileRemover.tsx
  4-presentation/my-app/src/components/Presentation/Slider/Contorller/index.tsx
  4-presentation/my-app/src/components/Presentation/Slider/ImageListSlider/Image.tsx
  4-presentation/my-app/src/components/Presentation/Slider/ImageListSlider/index.tsx
  4-presentation/my-app/src/components/Presentation/Slider/index.tsx
  4-presentation/my-app/src/components/Presentation/index.tsx
  4-presentation/my-app/src/constants/index.ts
  4-presentation/my-app/src/hooks/useFile.ts
  4-presentation/my-app/src/hooks/useSlider.ts
  4-presentation/my-app/src/index.tsx
  4-presentation/my-app/tsconfig.json
  4-presentation/my-app/webpack.config.js
Labels: 4th

#20 [DOTORI] 5번째 챌린지
  5-toast-notification/.eslintrc.js
  5-toast-notification/.prettierrc
  5-toast-notification/package-lock.json
  5-toast-notification/package.json
  5-toast-notification/public/index.html
  5-toast-notification/src/app.ts
  5-toast-notification/src/assets/cancel.svg
  5-toast-notification/src/assets/check-circle.svg
  5-toast-notification/src/assets/exclamation-triangle.svg
  5-toast-notification/src/assets/icons.ts
  5-toast-notification/src/assets/info-circle.svg
  5-toast-notification/src/assets/times-circle.svg
  5-toast-notification/src/components/ToastNotification/Notification.ts
  5-toast-notification/src/components/ToastNotification/Setter.ts
  5-toast-notification/src/components/ToastNotification/Stack.ts
  5-toast-notification/src/constants/index.ts
  5-toast-notification/src/custom.d.ts
  5-toast-notification/src/index.ts
  5-toast-notification/src/script.js
  5-toast-notification/src/style.css
  5-toast-notification/src/styles/reset.css
  5-toast-notification/src/styles/style.css
  5-toast-notification/src/utils/index.ts
  5-toast-notification/tsconfig.json
  5-toast-notification/webpack.config.js
Labels: 5th
